export type IconName =
  | 'heart'
  | 'lock'
  | 'message'
  | 'timer'
  | 'arrowRight'
  | 'arrowRightFill'
  | 'resultLine1'
  | 'resultLine2'
  | 'message-question'
  | 'lamp-on'
  | 'header-line'
  | 'quote-down'
  | 'quote-up'
  ;
